micronaut:
  application:
    name: grpcCarro
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/carro_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecret
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
